### ISSUE TITLE
Testing latest updates to Magnum, error with manifest dir option

### ISSUE THREAD

**Issue by sepulworld** [tehmaspc/magnum#19]
I am seeing this error with a freshly created module

==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Error: Could not parse application options: invalid option: --manifestdir
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by sepulworld** [comment]
I believe it is a problem with the version of Puppet on the default box provided being too new for the options passed in Vagrantfile

puppetlabs/ubuntu-14.04-64-puppet

**Comment by sepulworld** [comment]
This works:

I prefer to use hiera, but the other sections deal with environment settings which puppet 4 expects
```
  config.vm.provision :puppet do |puppet|
    puppet.environment_path = "spec"
    puppet.module_path = "spec/fixtures"
    puppet.environment = "fixtures"
    puppet.manifests_path = "./.vagrant_puppet"
    puppet.manifest_file  = "init.pp"
    puppet.hiera_config_path = "hiera/hiera.yaml"
    puppet.options = "--verbose"
  end
```

**Comment by tehmaspc** [comment]
yes; the new updates allow Magnum to work cleanly for Puppet 4.x. The `puppetlabs/ubuntu-14.04-64-puppet` box which I tested with and is the default box should be installing a recent 4.x Puppet agent. Are you using an old version of this box?: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet

**Comment by sepulworld** [comment]
Ah, I just realized I wasn't using the master branch.  Works well, sorry for the false issue.
